services:
  - type: web
    plan: free
    name: web-app
    runtime: node
    repo: https://github.com/M0UTOO/render-server
    buildCommand: "npm install; npm run build"
    startCommand: "npm run start"
    envVars:
      - key: DATABASE_URL # Sets DATABASE_URL to the connection string of the django-app-db database
        fromDatabase:
          name: render-db
          property: connectionString

databases:
  - name: render-db
    plan: free